---
driver:
  name: ec2
  instance_type: m3.medium
  security_group_ids: ["sg-e6b61680"] # open up rdp, winrm-http, winrm-https
  associate_public_ip: true
  interface: dns
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  tags:
    Name: kitchen-test-inspec-wannacry

transport:
  username: administrator
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

platforms:
  - name: windows-2012r2
